version: '3.8'

services:
  mcp-server:
    build: .
    container_name: knowledge-base-mcp
    ports:
      - "8050:8050"
    environment:
      - PORT=8050  # Match Railway configuration
    volumes:
      # Mount a volume for persistent data if needed
      - ./data:/app/data
    restart: unless-stopped

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: mcp-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - mcp-server
  #   restart: unless-stopped
