version: '3.8'

services:
  mcp-server:
    build: .
    container_name: knowledge-base-mcp
    ports:
      - "8050:8050"
    environment:
      # Add any environment variables your MCP server needs
      - NODE_ENV=production
      - PORT=8050  # Match Railway configuration
    volumes:
      # Mount a volume for persistent data if needed
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8050/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: mcp-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - mcp-server
  #   restart: unless-stopped
